bash scripts s3

diff --git a/bash-scripts/s3/delete-objects b/bash-scripts/s3/delete-objects
--- a/bash-scripts/s3/delete-objects
+++ b/bash-scripts/s3/delete-objects
@@ -1,12 +1,21 @@
 #!/usr/bin/env bash
-echo "==delete objects"
 
-#Check for bucket name
+# Check for bucket name
 if [ -z "$1" ]; then
-echo "There needs to be a bucket name ./bucket my-bucket-name"
-exit 1
+    echo "Error: No bucket name provided. Usage: ./script.sh my-bucket-name"
+    exit 1
 fi
 
 BUCKET_NAME=$1
 
-aws s3api delete-objects --bucket $BUCKET_NAME \
+# Check if there are objects in the bucket
+
+
+# List objects in the bucket and create JSON for deletion
+
+aws s3api list-objects-v2 \
+--bucket "$BUCKET_NAME" \
+--query Contents[].Key \
+| jq -n '{Objects: [inputs | .[] | {Key: . }]}' > /tmp/delete_objects.json
+
+aws s3api delete-objects --bucket "$BUCKET_NAME" --delete file:///tmp/delete_objects.json
diff --git a/bash-scripts/s3/put-object b/bash-scripts/s3/put-object
--- a/bash-scripts/s3/put-object
+++ b/bash-scripts/s3/put-object
@@ -17,7 +17,15 @@ for ((i = 1; i <= NUM_FILES; i++)); do
     touch "$FILE_NAME"
 done
 
-# Display the directory structure of OUTPUT_DIR
-tree "$OUTPUT_DIR"
+# Ensure BUCKET_NAME is passed as an argument
+if [ -z "$1" ]; then
+    echo "Error: No bucket name provided. Usage: ./put-object.sh my-bucket-name"
+    exit 1
+fi
+
+BUCKET_NAME=$1  # Get the bucket name from the argument
+
+# Debug output to verify bucket name
+echo "Bucket Name: $BUCKET_NAME"
 
 aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files
